# Generated by Django 3.2.6 on 2021-08-18 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('Enquiry', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_name', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('units', models.IntegerField(default=1, verbose_name='Quantity')),
                ('model_no', models.CharField(max_length=30, null=True, verbose_name='Model No')),
                ('eq_type', models.CharField(default='Cardio', max_length=30, verbose_name='Type')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('warranty', models.CharField(default='1 year', max_length=100, verbose_name='Warranty Period')),
                ('date_of_pur', models.DateField(default='2021-08-08', verbose_name='Date of Purchase')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField(default=18)),
                ('cell_no', models.IntegerField()),
                ('born_date', models.DateField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(default='Silver', max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Silver', max_length=10, verbose_name='Plan Name')),
                ('plan_type', models.CharField(default='Monthly', max_length=100, verbose_name='Type')),
                ('plan_amt', models.IntegerField(default=1000, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(default=1, max_length=100, verbose_name='Monday')),
                ('tue', models.CharField(default=1, max_length=100, verbose_name='Tuesday')),
                ('wed', models.CharField(default=1, max_length=100, verbose_name='Wednesday')),
                ('thu', models.CharField(default=1, max_length=100, verbose_name='Thursday')),
                ('fri', models.CharField(default=1, max_length=100, verbose_name='Friday')),
                ('sat', models.CharField(default=1, max_length=100, verbose_name='Saturday')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.trainers')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_status', models.BooleanField(default=False, verbose_name='Status')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym.gym', verbose_name='Member Name')),
            ],
        ),
    ]
