# Generated by Django 3.2.6 on 2021-09-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='pay_mode',
            field=models.CharField(default='Online', max_length=10, verbose_name='Payment Mode'),
        ),
    ]
