# Generated by Django 3.2 on 2021-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20210909_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='trans_id',
        ),
        migrations.AlterField(
            model_name='equipments',
            name='eq_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='warranty',
            field=models.CharField(default='1 year', max_length=10, verbose_name='Warranty Period'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='born_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gym',
            name='cell_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gender',
            field=models.CharField(default='Male', max_length=6, null=True),
        ),
    ]
