# Generated by Django 3.2 on 2021-10-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20211030_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
