# Generated by Django 3.2 on 2021-11-01 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_gym_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Payment Date'),
        ),
    ]
