# Generated by Django 3.2 on 2021-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20211101_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amt',
            field=models.IntegerField(default=1000),
        ),
    ]
