# Generated by Django 3.2.6 on 2021-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=30, verbose_name='Name')),
                ('trainer_age', models.IntegerField(verbose_name='Age')),
                ('trainer_gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('trainer_cell', models.IntegerField(null=True, verbose_name='Mobile No')),
                ('aos', models.CharField(max_length=100, verbose_name='Area of Specialization')),
                ('clients', models.IntegerField(verbose_name='Number of Clients')),
                ('salary', models.IntegerField(verbose_name='Salary')),
            ],
            options={
                'verbose_name_plural': 'Trainers',
            },
        ),
    ]
