# Generated by Django 3.2.6 on 2021-09-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='clients',
        ),
    ]
